receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  clickhouse:
    endpoint: https://clickhouse-single-http.ipp-dev.trendmicro.com:443
    database: ipplab
    username: default
    password: ipp1234
    ttl: 72h
    traces_table_name: otel_trace_lab
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  clickhouse/cluster:
    endpoint: tcp://10.132.124.249:9000,tcp://10.132.124.233:9000,tcp://10.132.124.244:9000
    database: ipplab_cluster_db
    username: default
    password:
    ttl: 72h
    traces_table_name: distributed_otel_trace_exporter
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

processors:
  batch:
    timeout: 1s
    send_batch_size: 30000

  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 20

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - batch
      exporters:
        - clickhouse
        # - clickhouse/cluster
        - otlp/jaeger
