version: "3"

networks:
  otel:

services:
  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    volumes:
      - "./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - otel

  ubt_traffic:
    image: otel
    ports:
      - "8888:8888"
    networks:
      - otel
