receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp/eks:
    endpoint: https://eks-otel-http.ipp-dev.trendmicro.com:443

  # clickhouse/cluster:
  #   endpoint: https://clickhouse-shard-http.ipp-dev.trendmicro.com:443
  #   database: ipplab
  #   username: ippadmin
  #   password: ippcluster81
  #   ttl: 72h
  #   traces_table_name: distributed_otel_trace_lab
  #   timeout: 5s
  #   retry_on_failure:
  #     enabled: true
  #     initial_interval: 5s
  #     max_interval: 30s
  #     max_elapsed_time: 300s

processors:
  batch:
    timeout: 1s
    send_batch_size: 30000

  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 20

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - batch
      exporters:
        # - clickhouse/cluster
        - otlphttp/eks
