receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint:
    tls:
      insecure: true

  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

processors:
  batch:

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
